import type { CatalogItem } from '../shared.js';
export const demoItems: CatalogItem[] = [
  [
    'books',
    'book',
    'The Atlas of Quiet Places',
    'Mira Vale',
    'A fictional field guide to hidden gardens, empty stations, and the places between journeys.',
    0.38,
  ],
  [
    'books',
    'audiobook',
    'A Sea of Small Stars',
    'Elias Wren',
    'A fictional voyage across a sea that remembers every traveler.',
    0.62,
  ],
  [
    'books',
    'book',
    'The Clockmaker’s Orchard',
    'June Alder',
    'A fictional story of seasons, inventions, and an orchard outside time.',
    0,
  ],
  [
    'books',
    'audiobook',
    'Letters from the North',
    'Rowan Ellis',
    'Fictional letters from a winter expedition, narrated beside a crackling fire.',
    0.17,
  ],
  [
    'books',
    'book',
    'Botany After Midnight',
    'Fern Moss',
    'A fictional illustrated guide to gardens that wake after dark.',
    0,
  ],
  [
    'books',
    'book',
    'The Last Paper Map',
    'Arthur Reed',
    'A fictional adventure through a changing city.',
    0,
  ],
  [
    'comics',
    'comic',
    'Moon Harbor · Volume 1',
    'Sora Finch',
    'A fictional comic about a harbor where moonlight becomes a tide.',
    0.45,
  ],
  [
    'comics',
    'comic',
    'Moon Harbor · Volume 2',
    'Sora Finch',
    'The fictional harbor opens its gates to a new visitor.',
    0,
  ],
  [
    'comics',
    'comic',
    'Lantern Courier · Volume 1',
    'Aki Vale',
    'A fictional manga about delivering letters between floating islands.',
    0.21,
  ],
  [
    'comics',
    'comic',
    'The Glass Forest',
    'Niko Ash',
    'A fictional illustrated journey into a forest of colored glass.',
    0,
  ],
  [
    'comics',
    'comic',
    'Cloudbound · Volume 1',
    'Remi Sky',
    'A fictional comic about a town above the weather.',
    0,
  ],
  [
    'movies',
    'movie',
    'The Observatory',
    'Lena Hart',
    'A fictional film about a retired astronomer and a mysterious signal.',
    0.52,
  ],
  [
    'movies',
    'show',
    'A House by the Tide',
    'Theo Bell',
    'A fictional television series set in a coastal boarding house.',
    0,
  ],
  [
    'movies',
    'episode',
    'A House by the Tide · The Visitor',
    'Theo Bell',
    'A fictional episode: a stranger arrives before the storm.',
    0.26,
  ],
  [
    'movies',
    'movie',
    'Across the Amber Field',
    'Noah Grove',
    'A fictional road movie following the longest day of summer.',
    0,
  ],
  [
    'movies',
    'movie',
    'Night Train to Anywhere',
    'Iris Stone',
    'A fictional mystery on a train without a destination.',
    0,
  ],
].map((row, i) => ({
  sourceId: 'demo',
  sourceItemId: `demo-${i}`,
  section: row[0],
  kind: row[1],
  title: row[2],
  creator: row[3],
  description: row[4],
  progress: Number(row[5]) > 0 ? { fraction: row[5], unit: 'fraction' } : undefined,
  actions: {
    open: 'unsupported',
    progress: Number(row[5]) > 0 ? 'supported' : 'unsupported',
    embeddedPlayback: 'unsupported',
  },
})) as CatalogItem[];
